

export const testFunc = async () => {
    try {

    } catch (error) {

    }
}